const ACTION_TYPES = {
  //CRUD

  //GET:
  GET_USERS_ACTION: 'GET_USERS_ACTION',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',

  //CREATE:
  CREATE_USERS_ACTION: 'CREATE_USERS_ACTION',
  CREATE_USERS_REQUEST: 'CREATE_USERS_REQUEST',
  CREATE_USERS_SUCCESS: 'CREATE_USERS_SUCCESS',
  CREATE_USERS_ERROR: 'CREATE_USERS_ERROR',

  //DELETE:
  DELETE_USERS_ACTION: 'DELETE_USERS_ACTION',
  DELETE_USERS_REQUEST: 'DELETE_USERS_REQUEST',
  DELETE_USERS_SUCCESS: 'DELETE_USERS_SUCCESS',
  DELETE_USERS_ERROR: 'DELETE_USERS_ERROR',

  //UPDATE:
};

export default ACTION_TYPES;
